os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10.0"
jdk:
  - oraclejdk8
cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.yarn-cache
    - node_modules
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=1
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - APP_FOLDER=$HOME/app
    - UAA_APP_FOLDER=$HOME/uaa
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
  # ----- ng1 applications -----
  # matrix:
  #   - JHIPSTER=app-mysql PROFILE=prod
  #   - JHIPSTER=app-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=app-social-websocket
  #   - JHIPSTER=app-hazelcast-cucumber
  #   - JHIPSTER=app-mariadb-kafka
  #   - JHIPSTER=app-cassandra
  #   - JHIPSTER=app-mongodb
  #   - JHIPSTER=app-oauth2
  #   - JHIPSTER=app-jwt
  #
  # ----- ng2 applications -----
  # matrix:
  #   - JHIPSTER=app-ng2-mysql PROFILE=prod
  #   - JHIPSTER=app-ng2-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=app-ng2-sass-noi18n
  #   - JHIPSTER=app-ng2-social-websocket
  #   - JHIPSTER=app-ng2-mariadb-kafka
  #   - JHIPSTER=app-ng2-cassandra
  #   - JHIPSTER=app-ng2-mongodb
  #   - JHIPSTER=app-ng2-oauth2
  #   - JHIPSTER=app-ng2-jwt
  #
  # ----- microservices applications -----
  # matrix:
  #   - JHIPSTER=app-ng2-gateway-eureka
  #   - JHIPSTER=app-ng2-gateway-consul
  #   - JHIPSTER=app-ng2-gateway-uaa
  #   - JHIPSTER=app-gateway-eureka
  #   - JHIPSTER=app-gateway-consul
  #   - JHIPSTER=app-gateway-uaa
  #   - JHIPSTER=app-microservice-eureka PROTRACTOR=0
  #   - JHIPSTER=app-microservice-consul PROTRACTOR=0
  #
  # ----- gradle applications -----
  # matrix:
  #   - JHIPSTER=app-gradle
  #   - JHIPSTER=app-gradle-mongodb
  #   - JHIPSTER=app-gradle-cassandra
  #   - JHIPSTER=app-gradle-gateway-eureka

before_install:
  - if [[ $JHIPSTER == "" ]]; then exit 0; fi;
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install with Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add yo bower gulp-cli
install:
  - $JHIPSTER_INSTALL/01-install-jhipster-stack.sh
  - $JHIPSTER_INSTALL/02-checkVersion.sh
  - $JHIPSTER_SCRIPTS/01-generate-entities.sh
  - $JHIPSTER_SCRIPTS/02-generate-project.sh
script:
  - $JHIPSTER_SCRIPTS/03-docker-compose.sh
  - $JHIPSTER_SCRIPTS/04-tests.sh
  - $JHIPSTER_SCRIPTS/05-run.sh
