os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "6.9.4"
jdk:
    - oraclejdk8
cache:
    yarn: true
    directories:
        - $HOME/.m2
        - $HOME/.gradle
        - $HOME/.yarn-cache
env:
    global:
        - PROFILE=dev
        - RUN_APP=1
        - PROTRACTOR=0
        - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
        - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
        - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
        - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    matrix:
        - JHIPSTER=app-default-from-scratch PROFILE=prod RUN_APP=0
        - JHIPSTER=app-gradle PROTRACTOR=1
        - JHIPSTER=app-mysql PROFILE=prod PROTRACTOR=1
        - JHIPSTER=app-psql-es-noi18n PROFILE=prod PROTRACTOR=1
        - JHIPSTER=app-social-websocket PROTRACTOR=1
        - JHIPSTER=app-hazelcast-cucumber
        - JHIPSTER=app-mariadb-kafka
        - JHIPSTER=app-gateway-eureka
        - JHIPSTER=app-gateway-consul
        - JHIPSTER=app-gateway-uaa
        - JHIPSTER=app-cassandra
        - JHIPSTER=app-mongodb
        - JHIPSTER=app-oauth2
        - JHIPSTER=app-jwt
        - JHIPSTER=app-microservice-eureka
        - JHIPSTER=app-microservice-consul
        - JHIPSTER=app-ng2-default PROTRACTOR=1
        - JHIPSTER=app-ng2-jwt PROTRACTOR=1
        - JHIPSTER=app-ng2-sass-noi18n PROTRACTOR=1

before_install:
    - export TZ=Australia/Canberra
    - date
    - sudo /etc/init.d/mysql stop
    - sudo /etc/init.d/postgresql stop
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Install with Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn global add yo bower gulp-cli
install:
    - $JHIPSTER_INSTALL/01-install-jhipster-stack.sh
    - $JHIPSTER_INSTALL/02-checkVersion.sh
script:
    - $JHIPSTER_SCRIPTS/01-generate-entities.sh
    - $JHIPSTER_SCRIPTS/02-generate-project.sh
    - $JHIPSTER_SCRIPTS/03-docker-compose.sh
    - $JHIPSTER_SCRIPTS/04-tests.sh
    - $JHIPSTER_SCRIPTS/05-run.sh
