os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.9.4"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=0
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/generator-jhipster/travis
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - APP_FOLDER=$HOME/app
    - UAA_APP_FOLDER=$HOME/uaa
    # environment properties
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
  # ----- ng1 applications -----
  # matrix:
  #   - JHIPSTER=ng1-mysql PROFILE=prod
  #   - JHIPSTER=ng1-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=ng1-social-websocket
  #   - JHIPSTER=ng1-hazelcast-cucumber
  #   - JHIPSTER=ng1-mariadb-kafka-nol2
  #   - JHIPSTER=ng1-cassandra
  #   - JHIPSTER=ng1-mongodb
  #   - JHIPSTER=ng1-session
  #   - JHIPSTER=ng1-infinispan
  #
  # ----- ngx applications -----
  # matrix:
  #   - JHIPSTER=ngx-mysql PROFILE=prod
  #   - JHIPSTER=ngx-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=ngx-sass-noi18n
  #   - JHIPSTER=ngx-social-websocket PROTRACTOR=0
  #   - JHIPSTER=ngx-hazelcast-cucumber
  #   - JHIPSTER=ngx-mariadb-kafka-nol2
  #   - JHIPSTER=ngx-cassandra
  #   - JHIPSTER=ngx-mongodb
  #   - JHIPSTER=ngx-oauth2
  #   - JHIPSTER=ngx-session
  #   - JHIPSTER=ngx-infinispan
  #   - JHIPSTER=ngx-couchbase
  #
  # ----- gradle applications -----
  # matrix:
  #   - JHIPSTER=gradle-ngx-mysql PROFILE=prod
  #   - JHIPSTER=gradle-ngx-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=gradle-ngx-sass-noi18n
  #   - JHIPSTER=gradle-ngx-social-websocket PROTRACTOR=0
  #   - JHIPSTER=gradle-ngx-hazelcast-cucumber
  #   - JHIPSTER=gradle-ngx-mariadb-kafka-nol2
  #   - JHIPSTER=gradle-ngx-cassandra
  #   - JHIPSTER=gradle-ngx-mongodb
  #   - JHIPSTER=gradle-ngx-oauth2
  #   - JHIPSTER=gradle-ngx-session
  #   - JHIPSTER=gradle-ngx-infinispan
  #   - JHIPSTER=gradle-ngx-couchbase
  #
  # ----- microservices applications -----
  # matrix:
  #   - JHIPSTER=ms-ngx-gateway-eureka
  #   - JHIPSTER=ms-ngx-gateway-consul
  #   - JHIPSTER=ms-ngx-gateway-uaa PROTRACTOR=0
  #   - JHIPSTER=ms-ng1-gateway-eureka
  #   - JHIPSTER=ms-ng1-gateway-consul
  #   - JHIPSTER=ms-ng1-gateway-uaa PROTRACTOR=0
  #   - JHIPSTER=ms-micro-eureka PROTRACTOR=0
  #   - JHIPSTER=ms-micro-consul PROTRACTOR=0
  #
  # ----- React applications -----
  # matrix:
  #   - JHIPSTER=react-mysql PROFILE=prod
  #   - JHIPSTER=react-psql-es-noi18n PROFILE=prod
  #   - JHIPSTER=react-sass-noi18n
  #   - JHIPSTER=react-social-websocket
  #   - JHIPSTER=react-mariadb-kafka
  #   - JHIPSTER=react-cassandra
  #   - JHIPSTER=react-mongodb
  #   - JHIPSTER=react-oauth2
  #   - JHIPSTER=react-session
  #   - JHIPSTER=react-infinispan
  #   - JHIPSTER=react-couchbase
  #
before_install:
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install with Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add yo bower gulp-cli
install:
  # install generator-jhipster from clone
  - travis/install-jhipster.sh
  - if [[ "$JHIPSTER" == "" ]]; then
      cd "$TRAVIS_BUILD_DIR"/generator-jhipster;
      yarn test;
    fi
  # copy samples
  - cp -R "$TRAVIS_BUILD_DIR"/travis/samples/* "$JHIPSTER_SAMPLES"/
  - ls -al "$JHIPSTER_SAMPLES"/
  - if [[ $JHIPSTER == "" ]]; then exit 0; fi;
  # generate project and entities
  - $JHIPSTER_SCRIPTS/01-generate-entities.sh
  - $JHIPSTER_SCRIPTS/02-generate-project.sh
script:
  - $JHIPSTER_SCRIPTS/03-docker-compose.sh
  - $JHIPSTER_SCRIPTS/04-tests.sh
  - $JHIPSTER_SCRIPTS/05-run.sh

# ----- Docker build
# before_install:
#   - docker version
# install:
#   - docker pull jhipster/jhipster:master
# script:
#   - docker run --rm -it jhipster/jhipster:master yarn --version
#   - docker run --rm -it jhipster/jhipster:master yo --version
#   - docker run --rm -it jhipster/jhipster:master bower --version
#   - docker run --rm -it jhipster/jhipster:master gulp --version
#   - docker run --rm -it jhipster/jhipster:master jhipster --help --no-insight
#   - docker run --rm -it jhipster/jhipster:master jhipster info --no-insight
